version: '2'
services:
  sqs:
    image: vsouza/sqs-local
    volumes:
      - ./docker/sqs/config/custom.conf:/custom.conf
    ports:
      - 41662:9324
  rabbitmq:
    build: ./docker/rabbitmq
    ports:
      - 29852:15672
      - 48888:5672
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
    environment:
      IS_DOCKER: 1
    volumes:
      - ./:/var/www/html/
      - ~/.composer/cache:/root/.composer/cache:cached
  wait:
    image: waisbrot/wait
    links:
      - rabbitmq
      - sqs
    environment:
      - TARGETS=rabbitmq:5672,sqs:9324